name: osx_kvm_installer
version: 0.0.10
homepage: https://github.com/relf108/OSX-KVM-installer
description: A cli based application which automates the installation and installation preperation steps required for the OSX-KVM project.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  args: ^1.0.0
  dcli: ^0.24.0
  path: ^1.0.0
  meta: ^1.2.2
dev_dependencies: 
  pedantic: ^1.0.0
executables: 
  osx_kvm_installer: null
